markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:title/
url: http://verraes.net
title: "Mathias Verraes' Blog"
description: "I'm Mathias Verraes. I build enterprise web applications, and I deal with complex legacy systems. This is my blog."