markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/
url: http://verraes.net
title: "Mathias Verraes' Blog"
description: "Student of Systems • Meddler of Models • Labourer of Legacy"